-- MySQL Script generated by MySQL Workbench
-- Fri Mar 29 09:54:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cotizador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cotizador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cotizador` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cotizador` ;

-- -----------------------------------------------------
-- Table `cotizador`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizador`.`empresa` (
  `idempresa` INT(11) NOT NULL AUTO_INCREMENT,
  `administrador` VARCHAR(45) NOT NULL,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `rut_empresa` VARCHAR(10) NOT NULL,
  `dv` VARCHAR(1) NOT NULL,
  `rubro_empresa` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `comuna` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizador`.`marca` (
  `idmarca` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizador`.`cotizacion` (
  `idcotizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `estado_cotizacion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `fecha_negocio` DATE NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `solicita` VARCHAR(45) NOT NULL,
  `EMPRESA_idempresa` INT(11) NOT NULL,
  `negocio_proyecto` VARCHAR(45) NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `tipo_unidad` VARCHAR(45) NOT NULL,
  `tipo_cabina` VARCHAR(45) NOT NULL,
  `traccion` VARCHAR(4) NOT NULL,
  `trasmision` VARCHAR(45) NOT NULL,
  `MARCA_idmarca` INT(11) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  `tipo_combustible` VARCHAR(45) NOT NULL,
  `lugar_entrega` LONGTEXT NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `plazo` INT(11) NOT NULL,
  `alarma_robo` VARCHAR(2) NOT NULL,
  `sensor_retroceso` VARCHAR(2) NOT NULL,
  `gps` VARCHAR(45) NOT NULL,
  `barras_antivuelco` VARCHAR(45) NOT NULL,
  `baliza` VARCHAR(45) NULL DEFAULT NULL,
  `laminas_seguridad` VARCHAR(45) NULL DEFAULT NULL,
  `cunas` VARCHAR(45) NULL DEFAULT NULL,
  `neumaticos` VARCHAR(45) NULL DEFAULT NULL,
  `pertiga` VARCHAR(45) NULL DEFAULT NULL,
  `portaescala` VARCHAR(45) NULL DEFAULT NULL,
  `cadena_nieve` VARCHAR(45) NULL DEFAULT NULL,
  `cupula` VARCHAR(45) NULL DEFAULT NULL,
  `bloqueo_elec` VARCHAR(45) NULL DEFAULT NULL,
  `parachoque` VARCHAR(45) NULL DEFAULT NULL,
  `cajaher` VARCHAR(45) NULL DEFAULT NULL,
  `malla_luneta` VARCHAR(45) NULL DEFAULT NULL,
  `cinta_reflec` VARCHAR(45) NULL DEFAULT NULL,
  `foco_faenero` VARCHAR(45) NULL DEFAULT NULL,
  `coco_arrastre` VARCHAR(45) NULL DEFAULT NULL,
  `2rueda` VARCHAR(45) NULL DEFAULT NULL,
  `extintor` VARCHAR(45) NULL DEFAULT NULL,
  `cubre_pickup` VARCHAR(45) NULL DEFAULT NULL,
  `seguro_tuerca` VARCHAR(45) NULL DEFAULT NULL,
  `estrobo` VARCHAR(45) NULL DEFAULT NULL,
  `kit_invierno` VARCHAR(45) NULL DEFAULT NULL,
  `neblinero` VARCHAR(45) NULL DEFAULT NULL,
  `soporte_neumatico` VARCHAR(45) NULL DEFAULT NULL,
  `tiro_arrastre` VARCHAR(45) NULL DEFAULT NULL,
  `observaciones` LONGTEXT NOT NULL,
  PRIMARY KEY (`idcotizacion`),
  INDEX `fk_COTIZACION_MARCA1_idx` (`MARCA_idmarca` ASC) VISIBLE,
  INDEX `fk_COTIZACION_EMPRESA1_idx` (`EMPRESA_idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_COTIZACION_EMPRESA1`
    FOREIGN KEY (`EMPRESA_idempresa`)
    REFERENCES `cotizador`.`empresa` (`idempresa`),
  CONSTRAINT `fk_COTIZACION_MARCA1`
    FOREIGN KEY (`MARCA_idmarca`)
    REFERENCES `cotizador`.`marca` (`idmarca`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizador`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `administrador` VARCHAR(45) NOT NULL,
  `nombre_coordinador` VARCHAR(45) NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizador`.`asignacion` (
  `idASIGNACION` INT(11) NOT NULL AUTO_INCREMENT,
  `COTIZACION_idcotizacion` INT(11) NOT NULL,
  `estado_cotizacion` VARCHAR(45) NOT NULL,
  `fecha_negocio` DATE NOT NULL,
  `fecha_asignacion` DATE NULL DEFAULT NULL,
  `USUARIO_idusuario` INT(11) NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idASIGNACION`),
  INDEX `fk_ASIGNACION_COTIZACION1_idx` (`COTIZACION_idcotizacion` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_USUARIO1_idx` (`USUARIO_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_ASIGNACION_COTIZACION1`
    FOREIGN KEY (`COTIZACION_idcotizacion`)
    REFERENCES `cotizador`.`cotizacion` (`idcotizacion`),
  CONSTRAINT `fk_ASIGNACION_USUARIO1`
    FOREIGN KEY (`USUARIO_idusuario`)
    REFERENCES `cotizador`.`usuario` (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`valorizar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cotizador`.`valorizar` (
  `idVALORIZAR` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `num_cotizacion` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  `observaciones` LONGTEXT NULL DEFAULT NULL,
  `ASIGNACION_idASIGNACION` INT(11) NOT NULL,
  PRIMARY KEY (`idVALORIZAR`),
  INDEX `fk_VALORIZAR_ASIGNACION1_idx` (`ASIGNACION_idASIGNACION` ASC) VISIBLE,
  CONSTRAINT `fk_VALORIZAR_ASIGNACION1`
    FOREIGN KEY (`ASIGNACION_idASIGNACION`)
    REFERENCES `cotizador`.`asignacion` (`idASIGNACION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `cotizador`;

DELIMITER $$
USE `cotizador`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `cotizador`.`tg_envio_cotizacion`
AFTER UPDATE ON `cotizador`.`cotizacion`
FOR EACH ROW
insert into asignacion 
(COTIZACION_idcotizacion,estado_cotizacion,fecha_negocio,fecha_asignacion,USUARIO_idusuario,usuario)
values 
(new.idcotizacion,new.estado_cotizacion,new.fecha,null,null,null)$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
